name: Deploy portfolio-one to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Hostinger to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz \
          --delete \
          --update \
          --compress-level=9 \
          --exclude ".git/" \
          --exclude ".github/" \
          --exclude ".env" \
          --exclude "portfolio-one/public/uploads" \
          -e "ssh -p ${{ secrets.SSH_PORT }}" \
          ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}/portfolio-one

      - name: Run Docker Compose
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
              cd ${{ secrets.SSH_PATH }} && \
              mkdir -p ./portfolio-one/public/uploads && \
              chmod 755 ./portfolio-one/public/uploads && \
              
            # Create a single .env file for both build and runtime
            echo 'DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"' > ./portfolio-one/.env && \
            echo 'AUTH_SECRET=\"${{ secrets.AUTH_SECRET }}\"' >> ./portfolio-one/.env && \
            echo 'NEXTAUTH_URL=\"https://deepakroy.dev\"' >> ./portfolio-one/.env && \
            echo 'NEXTAUTH_SECRET=\"${{ secrets.NEXTAUTH_SECRET }}\"' >> ./portfolio-one/.env && \
            echo 'GITHUB_CLIENT_ID=\"${{ secrets.GHUB_CLIENT_ID }}\"' >> ./portfolio-one/.env && \
            echo 'GITHUB_CLIENT_SECRET=\"${{ secrets.GHUB_CLIENT_SECRET }}\"' >> ./portfolio-one/.env && \
            echo 'GOOGLE_CLIENT_ID=\"${{ secrets.GOOGLE_CLIENT_ID }}\"' >> ./portfolio-one/.env && \
            echo 'GOOGLE_CLIENT_SECRET=\"${{ secrets.GOOGLE_CLIENT_SECRET }}\"' >> ./portfolio-one/.env && \
            echo 'NODE_ENV=\"production\"' >> ./portfolio-one/.env && \
            echo 'NEXT_PUBLIC_BASE_URL=\"https://deepakroy.dev\"' >> ./portfolio-one/.env && \
            echo 'RESEND_API_KEY=\"${{ secrets.RESEND_API_KEY }}\"' >> ./portfolio-one/.env && \
            echo 'FROM_EMAIL=\"${{ secrets.FROM_EMAIL }}\"' >> ./portfolio-one/.env && \
            echo 'CONTACT_EMAIL=\"${{ secrets.CONTACT_EMAIL }}\"' >> ./portfolio-one/.env && \

            # Run Docker Compose, which will automatically read the .env file
            # docker compose --env-file ./portfolio-one/.env up -d --build portfolio-one
            docker compose up -d --build portfolio-one
          "

      - name: Prune Docker Build Cache
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            docker builder prune --all --force
          "
